Support jest 28
vuejs/vue-jest pull request #468
Opened 2022-04-27 15:50 UTC by valentinpalkovic

fixes #467

[BREAKING CHANGE]: 
- Drop support for Jest 27
- Drop support for Node 10 (Drop Node 10 support as Jest 28 dropped it as well)
- Drop support for Typescript < 4.3 (Jest 28 requires Typescript >= 4.3)

2022-05-06 03:41 UTC, lmiller1990 commented
Nice job, I'll take a look at this soon.

2022-05-09 01:49 UTC, nogic1008 requested changes
Code fixes is LGTM, but docs need to update for clarify versioning.

2022-05-09 01:49 UTC, nogic1008 commented on README.md
> +| Vue 3       | Jest 28           | `@vue/vue3-jest` |
```suggestion
| Vue 2       | Jest 26 and below | `vue-jest@4`        |
| Vue 3       | Jest 26 and below | `vue-jest@5`        |
| Vue 2       | Jest 27 and above | `@vue/vue2-jest@xx` |
| Vue 3       | Jest 27 and above | `@vue/vue3-jest@xx` |

**xx**: Major version of Jest
```

2022-05-09 04:59 UTC, lmiller1990 commented
Once the docs is updated we can merge and release the Jest 28 support. 🙏

2022-05-09 06:38 UTC, lmiller1990 commented
Nice job @valentinpalkovic. Please give me a day or two to get this merged and released, since we need to also create the legacy 27.x branch before merging, and a few other things. I'm glad supporting Jest 28 was quite straight forward.

2022-05-09 08:17 UTC, nogic1008 approved these changes

2022-05-10 19:54 UTC, ScottAwesome commented
@lmiller1990 any chance of landing this in the next few days?

2022-05-10 23:55 UTC, lmiller1990 commented
I will probably be busy until the weekend, so it should be done by the start of next week.

2022-05-17 02:42 UTC, lmiller1990 commented
I will do this right now.

2022-05-17 02:48 UTC, lmiller1990 approved these changes

2022-05-17 02:48 UTC, merged

2022-05-17 03:14 UTC, lmiller1990 commented
It's out, please give it a try: https://github.com/vuejs/vue-jest/releases/tag/v28.0.0